services:
  backend:
    build: 
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mailhog
    networks:
      - backend-net
    volumes:
      - ./backend:/app 
      - /app/venv
  

  frontend:
    build:
      context: ./frontend 
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env 
    networks:
      - backend-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mailhog:
    image: mailhog/mailhog
    container_name: dev-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

